version: '3'

services:
  main-service:
    build: 
      context: .
      dockerfile: main_service/Dockerfile
    ports:
      - "5001:5000"
    networks:
      - safety-net

  cobot-service:
    build: 
      context: .
      dockerfile: cobot_service/Dockerfile
    ports:
      - "5002:5002"
    networks:
      - safety-net

  machine-service:
    build: 
      context: .
      dockerfile: machine_service/Dockerfile
    ports:
      - "5003:5002"
    networks:
      - safety-net

  ppe-service:
    build: 
      context: .
      dockerfile: ppe_service/Dockerfile
    ports:
      - "5004:5003"
    networks:
      - safety-net

  admin-dashboard:
    build:
      context: ./admin-dashboard
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_MAIN_SERVICE_URL=http://localhost:5001
      - NEXT_PUBLIC_COBOT_SERVICE_URL=http://cobot-service:5002
      - NEXT_PUBLIC_MACHINE_SERVICE_URL=http://machine-service:5002
      - NEXT_PUBLIC_PPE_SERVICE_URL=http://ppe-service:5003
    networks:
      - safety-net

networks:
  safety-net:
    driver: bridge
